apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-api-gateway
data:
  SERVER_PORT: "8080"
  BILL_SERVICE_URL: "http://bill-service"
  PRODUCT_SERVICE_URL: "http://product-service"
  USER_SERVICE_URL: "http://user-service"
  KOS_MOCK_URL: "http://kos-mock"