apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kos-mock
  template:
    metadata:
      labels:
        app: kos-mock
    spec:
      imagePullSecrets:
      - name: phonebill
      containers:
      - name: kos-mock
        image: acrdigitalgarage01.azurecr.io/phonebill/kos-mock:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: cm-common
        - configMapRef:
            name: cm-kos-mock
        - secretRef:
            name: secret-common
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3