apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
  
data:
  CORS_ALLOWED_ORIGINS: "http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084,http://phonebill-dg0511-api.20.249.191.180.nip.io"
  JWT_ACCESS_TOKEN_VALIDITY: "18000000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "dev"
  DDL_AUTO: "update"