apiVersion: v1
kind: Secret
metadata:
  name: secret-common
type: Opaque
stringData:
  JWT_SECRET: "nwe5Yo9qaJ6FBD/Thl2/j6/SFAfNwUorAY1ZcWO2KI7uA4bmVLOCPxE9hYuUpRCOkgV2UF2DdHXtqHi3+BU/ecbz2zpHyf/720h48UbA3XOMYOX1sdM+dQ=="
  REDIS_HOST: "redis-cache-dev-master"
  REDIS_PASSWORD: "Redis2025Dev@"